### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by kiwina** [b3nl/laravel-mwb-model#3]
Hi great idea this project, looking at the code i think you could simplify stuff by using the extended generators  laracasts/generators and crate the migration based on that as a string

**Comment by b3nl** [comment]
thx, will take a look.

**Comment by b3nl** [comment]
Yeah, i think that could be nice!

**Comment by b3nl** [comment]
Began with it in https://github.com/b3nl/laravel-mwb-model/compare/master...feature/3-laracast-generators
