### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by sombodi** [b3nl/laravel-mwb-model#5]
Can anyone please update the readme? I have no idea how to use this. It seems to be exactly what we need but we dont know how to use it
Thanks

**Comment by b3nl** [comment]
Will do it tomorrow!

**Comment by b3nl** [comment]
What do you think about: https://github.com/b3nl/laravel-mwb-model/blob/master/README.md ?

**Comment by sombodi** [comment]
Perfect! Thanks so much!
